// +build !ignore_autogenerated

/*
Copyright 2021 The Kruise Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagerState) DeepCopyInto(out *ManagerState) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagerState.
func (in *ManagerState) DeepCopy() *ManagerState {
	if in == nil {
		return nil
	}
	out := new(ManagerState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagerState) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagerStateEndpoint) DeepCopyInto(out *ManagerStateEndpoint) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagerStateEndpoint.
func (in *ManagerStateEndpoint) DeepCopy() *ManagerStateEndpoint {
	if in == nil {
		return nil
	}
	out := new(ManagerStateEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in ManagerStateEndpoints) DeepCopyInto(out *ManagerStateEndpoints) {
	{
		in := &in
		*out = make(ManagerStateEndpoints, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagerStateEndpoints.
func (in ManagerStateEndpoints) DeepCopy() ManagerStateEndpoints {
	if in == nil {
		return nil
	}
	out := new(ManagerStateEndpoints)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagerStateList) DeepCopyInto(out *ManagerStateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ManagerState, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagerStateList.
func (in *ManagerStateList) DeepCopy() *ManagerStateList {
	if in == nil {
		return nil
	}
	out := new(ManagerStateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagerStateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagerStatePorts) DeepCopyInto(out *ManagerStatePorts) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagerStatePorts.
func (in *ManagerStatePorts) DeepCopy() *ManagerStatePorts {
	if in == nil {
		return nil
	}
	out := new(ManagerStatePorts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagerStateSpec) DeepCopyInto(out *ManagerStateSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagerStateSpec.
func (in *ManagerStateSpec) DeepCopy() *ManagerStateSpec {
	if in == nil {
		return nil
	}
	out := new(ManagerStateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagerStateStatus) DeepCopyInto(out *ManagerStateStatus) {
	*out = *in
	if in.Endpoints != nil {
		in, out := &in.Endpoints, &out.Endpoints
		*out = make(ManagerStateEndpoints, len(*in))
		copy(*out, *in)
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = new(ManagerStatePorts)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagerStateStatus.
func (in *ManagerStateStatus) DeepCopy() *ManagerStateStatus {
	if in == nil {
		return nil
	}
	out := new(ManagerStateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MatchLimitSelector) DeepCopyInto(out *MatchLimitSelector) {
	*out = *in
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.NamespaceRegex != nil {
		in, out := &in.NamespaceRegex, &out.NamespaceRegex
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatchLimitSelector.
func (in *MatchLimitSelector) DeepCopy() *MatchLimitSelector {
	if in == nil {
		return nil
	}
	out := new(MatchLimitSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualApp) DeepCopyInto(out *VirtualApp) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualApp.
func (in *VirtualApp) DeepCopy() *VirtualApp {
	if in == nil {
		return nil
	}
	out := new(VirtualApp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualApp) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualAppConfiguration) DeepCopyInto(out *VirtualAppConfiguration) {
	*out = *in
	if in.Controller != nil {
		in, out := &in.Controller, &out.Controller
		*out = new(VirtualAppControllerConfiguration)
		**out = **in
	}
	if in.Webhook != nil {
		in, out := &in.Webhook, &out.Webhook
		*out = new(VirtualAppWebhookConfiguration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualAppConfiguration.
func (in *VirtualAppConfiguration) DeepCopy() *VirtualAppConfiguration {
	if in == nil {
		return nil
	}
	out := new(VirtualAppConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualAppControllerConfiguration) DeepCopyInto(out *VirtualAppControllerConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualAppControllerConfiguration.
func (in *VirtualAppControllerConfiguration) DeepCopy() *VirtualAppControllerConfiguration {
	if in == nil {
		return nil
	}
	out := new(VirtualAppControllerConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualAppList) DeepCopyInto(out *VirtualAppList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VirtualApp, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualAppList.
func (in *VirtualAppList) DeepCopy() *VirtualAppList {
	if in == nil {
		return nil
	}
	out := new(VirtualAppList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualAppList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualAppRoute) DeepCopyInto(out *VirtualAppRoute) {
	*out = *in
	if in.GlobalLimits != nil {
		in, out := &in.GlobalLimits, &out.GlobalLimits
		*out = make([]MatchLimitSelector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SubRules != nil {
		in, out := &in.SubRules, &out.SubRules
		*out = make([]VirtualAppRouteSubRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualAppRoute.
func (in *VirtualAppRoute) DeepCopy() *VirtualAppRoute {
	if in == nil {
		return nil
	}
	out := new(VirtualAppRoute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualAppRouteSubRule) DeepCopyInto(out *VirtualAppRouteSubRule) {
	*out = *in
	if in.Match != nil {
		in, out := &in.Match, &out.Match
		*out = make([]MatchLimitSelector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualAppRouteSubRule.
func (in *VirtualAppRouteSubRule) DeepCopy() *VirtualAppRouteSubRule {
	if in == nil {
		return nil
	}
	out := new(VirtualAppRouteSubRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualAppSpec) DeepCopyInto(out *VirtualAppSpec) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Configuration != nil {
		in, out := &in.Configuration, &out.Configuration
		*out = new(VirtualAppConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Route != nil {
		in, out := &in.Route, &out.Route
		*out = new(VirtualAppRoute)
		(*in).DeepCopyInto(*out)
	}
	if in.Subsets != nil {
		in, out := &in.Subsets, &out.Subsets
		*out = make([]VirtualAppSubset, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualAppSpec.
func (in *VirtualAppSpec) DeepCopy() *VirtualAppSpec {
	if in == nil {
		return nil
	}
	out := new(VirtualAppSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualAppStatus) DeepCopyInto(out *VirtualAppStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualAppStatus.
func (in *VirtualAppStatus) DeepCopy() *VirtualAppStatus {
	if in == nil {
		return nil
	}
	out := new(VirtualAppStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualAppSubset) DeepCopyInto(out *VirtualAppSubset) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.RouteRules != nil {
		in, out := &in.RouteRules, &out.RouteRules
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualAppSubset.
func (in *VirtualAppSubset) DeepCopy() *VirtualAppSubset {
	if in == nil {
		return nil
	}
	out := new(VirtualAppSubset)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualAppWebhookConfiguration) DeepCopyInto(out *VirtualAppWebhookConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualAppWebhookConfiguration.
func (in *VirtualAppWebhookConfiguration) DeepCopy() *VirtualAppWebhookConfiguration {
	if in == nil {
		return nil
	}
	out := new(VirtualAppWebhookConfiguration)
	in.DeepCopyInto(out)
	return out
}
