/*
Copyright 2021 The Kruise Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/openkruise/controllermesh/apis/ctrlmesh/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeTrafficPolicies implements TrafficPolicyInterface
type FakeTrafficPolicies struct {
	Fake *FakeCtrlmeshV1alpha1
	ns   string
}

var trafficpoliciesResource = schema.GroupVersionResource{Group: "ctrlmesh.kruise.io", Version: "v1alpha1", Resource: "trafficpolicies"}

var trafficpoliciesKind = schema.GroupVersionKind{Group: "ctrlmesh.kruise.io", Version: "v1alpha1", Kind: "TrafficPolicy"}

// Get takes name of the trafficPolicy, and returns the corresponding trafficPolicy object, and an error if there is any.
func (c *FakeTrafficPolicies) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.TrafficPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(trafficpoliciesResource, c.ns, name), &v1alpha1.TrafficPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TrafficPolicy), err
}

// List takes label and field selectors, and returns the list of TrafficPolicies that match those selectors.
func (c *FakeTrafficPolicies) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.TrafficPolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(trafficpoliciesResource, trafficpoliciesKind, c.ns, opts), &v1alpha1.TrafficPolicyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.TrafficPolicyList{ListMeta: obj.(*v1alpha1.TrafficPolicyList).ListMeta}
	for _, item := range obj.(*v1alpha1.TrafficPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested trafficPolicies.
func (c *FakeTrafficPolicies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(trafficpoliciesResource, c.ns, opts))

}

// Create takes the representation of a trafficPolicy and creates it.  Returns the server's representation of the trafficPolicy, and an error, if there is any.
func (c *FakeTrafficPolicies) Create(ctx context.Context, trafficPolicy *v1alpha1.TrafficPolicy, opts v1.CreateOptions) (result *v1alpha1.TrafficPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(trafficpoliciesResource, c.ns, trafficPolicy), &v1alpha1.TrafficPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TrafficPolicy), err
}

// Update takes the representation of a trafficPolicy and updates it. Returns the server's representation of the trafficPolicy, and an error, if there is any.
func (c *FakeTrafficPolicies) Update(ctx context.Context, trafficPolicy *v1alpha1.TrafficPolicy, opts v1.UpdateOptions) (result *v1alpha1.TrafficPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(trafficpoliciesResource, c.ns, trafficPolicy), &v1alpha1.TrafficPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TrafficPolicy), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeTrafficPolicies) UpdateStatus(ctx context.Context, trafficPolicy *v1alpha1.TrafficPolicy, opts v1.UpdateOptions) (*v1alpha1.TrafficPolicy, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(trafficpoliciesResource, "status", c.ns, trafficPolicy), &v1alpha1.TrafficPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TrafficPolicy), err
}

// Delete takes name of the trafficPolicy and deletes it. Returns an error if one occurs.
func (c *FakeTrafficPolicies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(trafficpoliciesResource, c.ns, name), &v1alpha1.TrafficPolicy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeTrafficPolicies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(trafficpoliciesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.TrafficPolicyList{})
	return err
}

// Patch applies the patch and returns the patched trafficPolicy.
func (c *FakeTrafficPolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.TrafficPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(trafficpoliciesResource, c.ns, name, pt, data, subresources...), &v1alpha1.TrafficPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TrafficPolicy), err
}
