/*
Copyright 2021 The Kruise Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/openkruise/controllermesh/apis/ctrlmesh/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeClusterMetas implements ClusterMetaInterface
type FakeClusterMetas struct {
	Fake *FakeCtrlmeshV1alpha1
}

var clustermetasResource = schema.GroupVersionResource{Group: "ctrlmesh.kruise.io", Version: "v1alpha1", Resource: "clustermetas"}

var clustermetasKind = schema.GroupVersionKind{Group: "ctrlmesh.kruise.io", Version: "v1alpha1", Kind: "ClusterMeta"}

// Get takes name of the clusterMeta, and returns the corresponding clusterMeta object, and an error if there is any.
func (c *FakeClusterMetas) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ClusterMeta, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(clustermetasResource, name), &v1alpha1.ClusterMeta{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterMeta), err
}

// List takes label and field selectors, and returns the list of ClusterMetas that match those selectors.
func (c *FakeClusterMetas) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ClusterMetaList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(clustermetasResource, clustermetasKind, opts), &v1alpha1.ClusterMetaList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ClusterMetaList{ListMeta: obj.(*v1alpha1.ClusterMetaList).ListMeta}
	for _, item := range obj.(*v1alpha1.ClusterMetaList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested clusterMetas.
func (c *FakeClusterMetas) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(clustermetasResource, opts))
}

// Create takes the representation of a clusterMeta and creates it.  Returns the server's representation of the clusterMeta, and an error, if there is any.
func (c *FakeClusterMetas) Create(ctx context.Context, clusterMeta *v1alpha1.ClusterMeta, opts v1.CreateOptions) (result *v1alpha1.ClusterMeta, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(clustermetasResource, clusterMeta), &v1alpha1.ClusterMeta{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterMeta), err
}

// Update takes the representation of a clusterMeta and updates it. Returns the server's representation of the clusterMeta, and an error, if there is any.
func (c *FakeClusterMetas) Update(ctx context.Context, clusterMeta *v1alpha1.ClusterMeta, opts v1.UpdateOptions) (result *v1alpha1.ClusterMeta, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(clustermetasResource, clusterMeta), &v1alpha1.ClusterMeta{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterMeta), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeClusterMetas) UpdateStatus(ctx context.Context, clusterMeta *v1alpha1.ClusterMeta, opts v1.UpdateOptions) (*v1alpha1.ClusterMeta, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(clustermetasResource, "status", clusterMeta), &v1alpha1.ClusterMeta{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterMeta), err
}

// Delete takes name of the clusterMeta and deletes it. Returns an error if one occurs.
func (c *FakeClusterMetas) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(clustermetasResource, name), &v1alpha1.ClusterMeta{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeClusterMetas) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(clustermetasResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ClusterMetaList{})
	return err
}

// Patch applies the patch and returns the patched clusterMeta.
func (c *FakeClusterMetas) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterMeta, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(clustermetasResource, name, pt, data, subresources...), &v1alpha1.ClusterMeta{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterMeta), err
}
