apiVersion: v1
clusters:
  - cluster:
      insecure-skip-tls-verify: true
      server: http://127.0.0.1:5443
    name: fake-cluster
contexts:
  - context:
      cluster: fake-cluster
      namespace: fake-namespace
      user: fake-user
    name: fake-context
current-context: fake-context
kind: Config
preferences: {}
users:
  - name: fake-user
    user:
      username:
      password: