/*
Copyright 2021 The Kruise Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	ctrlmeshv1alpha1 "github.com/openkruise/controllermesh/apis/ctrlmesh/v1alpha1"
	versioned "github.com/openkruise/controllermesh/client/clientset/versioned"
	internalinterfaces "github.com/openkruise/controllermesh/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/openkruise/controllermesh/client/listers/ctrlmesh/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// VirtualAppInformer provides access to a shared informer and lister for
// VirtualApps.
type VirtualAppInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.VirtualAppLister
}

type virtualAppInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewVirtualAppInformer constructs a new informer for VirtualApp type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewVirtualAppInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredVirtualAppInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredVirtualAppInformer constructs a new informer for VirtualApp type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredVirtualAppInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CtrlmeshV1alpha1().VirtualApps(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CtrlmeshV1alpha1().VirtualApps(namespace).Watch(context.TODO(), options)
			},
		},
		&ctrlmeshv1alpha1.VirtualApp{},
		resyncPeriod,
		indexers,
	)
}

func (f *virtualAppInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredVirtualAppInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *virtualAppInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&ctrlmeshv1alpha1.VirtualApp{}, f.defaultInformer)
}

func (f *virtualAppInformer) Lister() v1alpha1.VirtualAppLister {
	return v1alpha1.NewVirtualAppLister(f.Informer().GetIndexer())
}
