// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: apis/ctrlmesh/proto/ctrlmesh.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ProxyStatus struct {
	SelfInfo             *SelfInfo           `protobuf:"bytes,1,opt,name=selfInfo,proto3" json:"selfInfo,omitempty"`
	SpecHash             *SpecHash           `protobuf:"bytes,2,opt,name=specHash,proto3" json:"specHash,omitempty"`
	ControlInstruction   *ControlInstruction `protobuf:"bytes,3,opt,name=controlInstruction,proto3" json:"controlInstruction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ProxyStatus) Reset()         { *m = ProxyStatus{} }
func (m *ProxyStatus) String() string { return proto.CompactTextString(m) }
func (*ProxyStatus) ProtoMessage()    {}
func (*ProxyStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_015120ea8d6d1ea6, []int{0}
}
func (m *ProxyStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyStatus.Unmarshal(m, b)
}
func (m *ProxyStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyStatus.Marshal(b, m, deterministic)
}
func (m *ProxyStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyStatus.Merge(m, src)
}
func (m *ProxyStatus) XXX_Size() int {
	return xxx_messageInfo_ProxyStatus.Size(m)
}
func (m *ProxyStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyStatus proto.InternalMessageInfo

func (m *ProxyStatus) GetSelfInfo() *SelfInfo {
	if m != nil {
		return m.SelfInfo
	}
	return nil
}

func (m *ProxyStatus) GetSpecHash() *SpecHash {
	if m != nil {
		return m.SpecHash
	}
	return nil
}

func (m *ProxyStatus) GetControlInstruction() *ControlInstruction {
	if m != nil {
		return m.ControlInstruction
	}
	return nil
}

type SelfInfo struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SelfInfo) Reset()         { *m = SelfInfo{} }
func (m *SelfInfo) String() string { return proto.CompactTextString(m) }
func (*SelfInfo) ProtoMessage()    {}
func (*SelfInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_015120ea8d6d1ea6, []int{1}
}
func (m *SelfInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelfInfo.Unmarshal(m, b)
}
func (m *SelfInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelfInfo.Marshal(b, m, deterministic)
}
func (m *SelfInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelfInfo.Merge(m, src)
}
func (m *SelfInfo) XXX_Size() int {
	return xxx_messageInfo_SelfInfo.Size(m)
}
func (m *SelfInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SelfInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SelfInfo proto.InternalMessageInfo

func (m *SelfInfo) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *SelfInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type SpecHash struct {
	ResourceVersion      string   `protobuf:"bytes,1,opt,name=resourceVersion,proto3" json:"resourceVersion,omitempty"`
	RouteHash            string   `protobuf:"bytes,2,opt,name=routeHash,proto3" json:"routeHash,omitempty"`
	RouteStrictHash      string   `protobuf:"bytes,3,opt,name=routeStrictHash,proto3" json:"routeStrictHash,omitempty"`
	EndpointsHash        string   `protobuf:"bytes,4,opt,name=endpointsHash,proto3" json:"endpointsHash,omitempty"`
	NamespacesHash       string   `protobuf:"bytes,5,opt,name=namespacesHash,proto3" json:"namespacesHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SpecHash) Reset()         { *m = SpecHash{} }
func (m *SpecHash) String() string { return proto.CompactTextString(m) }
func (*SpecHash) ProtoMessage()    {}
func (*SpecHash) Descriptor() ([]byte, []int) {
	return fileDescriptor_015120ea8d6d1ea6, []int{2}
}
func (m *SpecHash) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpecHash.Unmarshal(m, b)
}
func (m *SpecHash) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpecHash.Marshal(b, m, deterministic)
}
func (m *SpecHash) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpecHash.Merge(m, src)
}
func (m *SpecHash) XXX_Size() int {
	return xxx_messageInfo_SpecHash.Size(m)
}
func (m *SpecHash) XXX_DiscardUnknown() {
	xxx_messageInfo_SpecHash.DiscardUnknown(m)
}

var xxx_messageInfo_SpecHash proto.InternalMessageInfo

func (m *SpecHash) GetResourceVersion() string {
	if m != nil {
		return m.ResourceVersion
	}
	return ""
}

func (m *SpecHash) GetRouteHash() string {
	if m != nil {
		return m.RouteHash
	}
	return ""
}

func (m *SpecHash) GetRouteStrictHash() string {
	if m != nil {
		return m.RouteStrictHash
	}
	return ""
}

func (m *SpecHash) GetEndpointsHash() string {
	if m != nil {
		return m.EndpointsHash
	}
	return ""
}

func (m *SpecHash) GetNamespacesHash() string {
	if m != nil {
		return m.NamespacesHash
	}
	return ""
}

type ProxySpec struct {
	Meta                 *VAppMeta           `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Route                *Route              `protobuf:"bytes,2,opt,name=route,proto3" json:"route,omitempty"`
	Endpoints            []*Endpoint         `protobuf:"bytes,3,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	ControlInstruction   *ControlInstruction `protobuf:"bytes,4,opt,name=controlInstruction,proto3" json:"controlInstruction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ProxySpec) Reset()         { *m = ProxySpec{} }
func (m *ProxySpec) String() string { return proto.CompactTextString(m) }
func (*ProxySpec) ProtoMessage()    {}
func (*ProxySpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_015120ea8d6d1ea6, []int{3}
}
func (m *ProxySpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxySpec.Unmarshal(m, b)
}
func (m *ProxySpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxySpec.Marshal(b, m, deterministic)
}
func (m *ProxySpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxySpec.Merge(m, src)
}
func (m *ProxySpec) XXX_Size() int {
	return xxx_messageInfo_ProxySpec.Size(m)
}
func (m *ProxySpec) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxySpec.DiscardUnknown(m)
}

var xxx_messageInfo_ProxySpec proto.InternalMessageInfo

func (m *ProxySpec) GetMeta() *VAppMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *ProxySpec) GetRoute() *Route {
	if m != nil {
		return m.Route
	}
	return nil
}

func (m *ProxySpec) GetEndpoints() []*Endpoint {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

func (m *ProxySpec) GetControlInstruction() *ControlInstruction {
	if m != nil {
		return m.ControlInstruction
	}
	return nil
}

type VAppMeta struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ResourceVersion      string   `protobuf:"bytes,3,opt,name=resourceVersion,proto3" json:"resourceVersion,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VAppMeta) Reset()         { *m = VAppMeta{} }
func (m *VAppMeta) String() string { return proto.CompactTextString(m) }
func (*VAppMeta) ProtoMessage()    {}
func (*VAppMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_015120ea8d6d1ea6, []int{4}
}
func (m *VAppMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VAppMeta.Unmarshal(m, b)
}
func (m *VAppMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VAppMeta.Marshal(b, m, deterministic)
}
func (m *VAppMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VAppMeta.Merge(m, src)
}
func (m *VAppMeta) XXX_Size() int {
	return xxx_messageInfo_VAppMeta.Size(m)
}
func (m *VAppMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_VAppMeta.DiscardUnknown(m)
}

var xxx_messageInfo_VAppMeta proto.InternalMessageInfo

func (m *VAppMeta) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *VAppMeta) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *VAppMeta) GetResourceVersion() string {
	if m != nil {
		return m.ResourceVersion
	}
	return ""
}

type Route struct {
	Subset                  string                  `protobuf:"bytes,1,opt,name=subset,proto3" json:"subset,omitempty"`
	GlobalLimits            string                  `protobuf:"bytes,2,opt,name=globalLimits,proto3" json:"globalLimits,omitempty"`
	SubRules                string                  `protobuf:"bytes,3,opt,name=subRules,proto3" json:"subRules,omitempty"`
	Subsets                 string                  `protobuf:"bytes,4,opt,name=subsets,proto3" json:"subsets,omitempty"`
	GlobalExcludeNamespaces []string                `protobuf:"bytes,5,rep,name=globalExcludeNamespaces,proto3" json:"globalExcludeNamespaces,omitempty"`
	SensSubsetNamespaces    []*SensSubsetNamespaces `protobuf:"bytes,6,rep,name=sensSubsetNamespaces,proto3" json:"sensSubsetNamespaces,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}                `json:"-"`
	XXX_unrecognized        []byte                  `json:"-"`
	XXX_sizecache           int32                   `json:"-"`
}

func (m *Route) Reset()         { *m = Route{} }
func (m *Route) String() string { return proto.CompactTextString(m) }
func (*Route) ProtoMessage()    {}
func (*Route) Descriptor() ([]byte, []int) {
	return fileDescriptor_015120ea8d6d1ea6, []int{5}
}
func (m *Route) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Route.Unmarshal(m, b)
}
func (m *Route) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Route.Marshal(b, m, deterministic)
}
func (m *Route) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Route.Merge(m, src)
}
func (m *Route) XXX_Size() int {
	return xxx_messageInfo_Route.Size(m)
}
func (m *Route) XXX_DiscardUnknown() {
	xxx_messageInfo_Route.DiscardUnknown(m)
}

var xxx_messageInfo_Route proto.InternalMessageInfo

func (m *Route) GetSubset() string {
	if m != nil {
		return m.Subset
	}
	return ""
}

func (m *Route) GetGlobalLimits() string {
	if m != nil {
		return m.GlobalLimits
	}
	return ""
}

func (m *Route) GetSubRules() string {
	if m != nil {
		return m.SubRules
	}
	return ""
}

func (m *Route) GetSubsets() string {
	if m != nil {
		return m.Subsets
	}
	return ""
}

func (m *Route) GetGlobalExcludeNamespaces() []string {
	if m != nil {
		return m.GlobalExcludeNamespaces
	}
	return nil
}

func (m *Route) GetSensSubsetNamespaces() []*SensSubsetNamespaces {
	if m != nil {
		return m.SensSubsetNamespaces
	}
	return nil
}

type SensSubsetNamespaces struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespaces           []string `protobuf:"bytes,2,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SensSubsetNamespaces) Reset()         { *m = SensSubsetNamespaces{} }
func (m *SensSubsetNamespaces) String() string { return proto.CompactTextString(m) }
func (*SensSubsetNamespaces) ProtoMessage()    {}
func (*SensSubsetNamespaces) Descriptor() ([]byte, []int) {
	return fileDescriptor_015120ea8d6d1ea6, []int{6}
}
func (m *SensSubsetNamespaces) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SensSubsetNamespaces.Unmarshal(m, b)
}
func (m *SensSubsetNamespaces) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SensSubsetNamespaces.Marshal(b, m, deterministic)
}
func (m *SensSubsetNamespaces) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SensSubsetNamespaces.Merge(m, src)
}
func (m *SensSubsetNamespaces) XXX_Size() int {
	return xxx_messageInfo_SensSubsetNamespaces.Size(m)
}
func (m *SensSubsetNamespaces) XXX_DiscardUnknown() {
	xxx_messageInfo_SensSubsetNamespaces.DiscardUnknown(m)
}

var xxx_messageInfo_SensSubsetNamespaces proto.InternalMessageInfo

func (m *SensSubsetNamespaces) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SensSubsetNamespaces) GetNamespaces() []string {
	if m != nil {
		return m.Namespaces
	}
	return nil
}

type Endpoint struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Subset               string   `protobuf:"bytes,2,opt,name=subset,proto3" json:"subset,omitempty"`
	Ip                   string   `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Endpoint) Reset()         { *m = Endpoint{} }
func (m *Endpoint) String() string { return proto.CompactTextString(m) }
func (*Endpoint) ProtoMessage()    {}
func (*Endpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_015120ea8d6d1ea6, []int{7}
}
func (m *Endpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Endpoint.Unmarshal(m, b)
}
func (m *Endpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Endpoint.Marshal(b, m, deterministic)
}
func (m *Endpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Endpoint.Merge(m, src)
}
func (m *Endpoint) XXX_Size() int {
	return xxx_messageInfo_Endpoint.Size(m)
}
func (m *Endpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_Endpoint.DiscardUnknown(m)
}

var xxx_messageInfo_Endpoint proto.InternalMessageInfo

func (m *Endpoint) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Endpoint) GetSubset() string {
	if m != nil {
		return m.Subset
	}
	return ""
}

func (m *Endpoint) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type ControlInstruction struct {
	BlockLeaderElection  bool     `protobuf:"varint,1,opt,name=blockLeaderElection,proto3" json:"blockLeaderElection,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ControlInstruction) Reset()         { *m = ControlInstruction{} }
func (m *ControlInstruction) String() string { return proto.CompactTextString(m) }
func (*ControlInstruction) ProtoMessage()    {}
func (*ControlInstruction) Descriptor() ([]byte, []int) {
	return fileDescriptor_015120ea8d6d1ea6, []int{8}
}
func (m *ControlInstruction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ControlInstruction.Unmarshal(m, b)
}
func (m *ControlInstruction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ControlInstruction.Marshal(b, m, deterministic)
}
func (m *ControlInstruction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ControlInstruction.Merge(m, src)
}
func (m *ControlInstruction) XXX_Size() int {
	return xxx_messageInfo_ControlInstruction.Size(m)
}
func (m *ControlInstruction) XXX_DiscardUnknown() {
	xxx_messageInfo_ControlInstruction.DiscardUnknown(m)
}

var xxx_messageInfo_ControlInstruction proto.InternalMessageInfo

func (m *ControlInstruction) GetBlockLeaderElection() bool {
	if m != nil {
		return m.BlockLeaderElection
	}
	return false
}

func init() {
	proto.RegisterType((*ProxyStatus)(nil), "proto.ProxyStatus")
	proto.RegisterType((*SelfInfo)(nil), "proto.SelfInfo")
	proto.RegisterType((*SpecHash)(nil), "proto.SpecHash")
	proto.RegisterType((*ProxySpec)(nil), "proto.ProxySpec")
	proto.RegisterType((*VAppMeta)(nil), "proto.VAppMeta")
	proto.RegisterType((*Route)(nil), "proto.Route")
	proto.RegisterType((*SensSubsetNamespaces)(nil), "proto.SensSubsetNamespaces")
	proto.RegisterType((*Endpoint)(nil), "proto.Endpoint")
	proto.RegisterType((*ControlInstruction)(nil), "proto.ControlInstruction")
}

func init() {
	proto.RegisterFile("apis/ctrlmesh/proto/ctrlmesh.proto", fileDescriptor_015120ea8d6d1ea6)
}

var fileDescriptor_015120ea8d6d1ea6 = []byte{
	// 580 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x51, 0x6b, 0xd4, 0x4c,
	0x14, 0xfd, 0x92, 0x6c, 0xda, 0xe4, 0xb6, 0x5f, 0x2b, 0xd7, 0xa2, 0xb1, 0x8a, 0x94, 0x51, 0x64,
	0x41, 0x6c, 0x4b, 0x05, 0xf1, 0xc1, 0x17, 0x95, 0x96, 0x56, 0x5a, 0x95, 0x59, 0xe8, 0x83, 0x0f,
	0x42, 0x36, 0x7b, 0xdb, 0x0d, 0xcd, 0x66, 0xc2, 0xcc, 0x04, 0xea, 0xbb, 0xbf, 0xc8, 0x9f, 0xe1,
	0x83, 0xbf, 0x49, 0x32, 0x99, 0x64, 0x37, 0xbb, 0xe9, 0x8b, 0x4f, 0xd9, 0x7b, 0xe6, 0xdc, 0x33,
	0x67, 0xee, 0x99, 0x1d, 0x60, 0x71, 0x91, 0xaa, 0x83, 0x44, 0xcb, 0x6c, 0x46, 0x6a, 0x7a, 0x50,
	0x48, 0xa1, 0x45, 0x5b, 0xee, 0x9b, 0x12, 0x7d, 0xf3, 0x61, 0xbf, 0x1c, 0xd8, 0xf8, 0x2a, 0xc5,
	0xed, 0x8f, 0x91, 0x8e, 0x75, 0xa9, 0xf0, 0x25, 0x04, 0x8a, 0xb2, 0xab, 0xb3, 0xfc, 0x4a, 0x44,
	0xce, 0x9e, 0x33, 0xdc, 0x38, 0xda, 0xae, 0x1b, 0xf6, 0x47, 0x16, 0xe6, 0x2d, 0xc1, 0x90, 0x0b,
	0x4a, 0x4e, 0x63, 0x35, 0x8d, 0xdc, 0x2e, 0xd9, 0xc2, 0xbc, 0x25, 0xe0, 0x19, 0x60, 0x22, 0x72,
	0x2d, 0x45, 0x76, 0x96, 0x2b, 0x2d, 0xcb, 0x44, 0xa7, 0x22, 0x8f, 0x3c, 0xd3, 0xf6, 0xc8, 0xb6,
	0x7d, 0x5c, 0x21, 0xf0, 0x9e, 0x26, 0xf6, 0x0e, 0x82, 0xc6, 0x0d, 0x3e, 0x81, 0x30, 0x8f, 0x67,
	0xa4, 0x8a, 0x38, 0x21, 0xe3, 0x38, 0xe4, 0x73, 0x00, 0x11, 0x06, 0x55, 0x61, 0xdc, 0x85, 0xdc,
	0xfc, 0x66, 0xbf, 0x1d, 0x08, 0x1a, 0x7f, 0x38, 0x84, 0x6d, 0x49, 0x4a, 0x94, 0x32, 0xa1, 0x4b,
	0x92, 0xaa, 0xb2, 0x54, 0x8b, 0x2c, 0xc3, 0xd5, 0x46, 0x52, 0x94, 0x9a, 0xda, 0xd3, 0x86, 0x7c,
	0x0e, 0x18, 0x9d, 0xaa, 0x18, 0x69, 0x99, 0x26, 0xda, 0x70, 0x3c, 0xab, 0xd3, 0x85, 0xf1, 0x39,
	0xfc, 0x4f, 0xf9, 0xa4, 0x10, 0x69, 0xae, 0x95, 0xe1, 0x0d, 0x0c, 0xaf, 0x0b, 0xe2, 0x0b, 0xd8,
	0x6a, 0x4f, 0x51, 0xd3, 0x7c, 0x43, 0x5b, 0x42, 0xd9, 0x1f, 0x07, 0xc2, 0x3a, 0xbf, 0x82, 0x12,
	0x7c, 0x06, 0x83, 0x19, 0xe9, 0x78, 0x29, 0xb9, 0xcb, 0xf7, 0x45, 0x71, 0x41, 0x3a, 0xe6, 0x66,
	0x11, 0x19, 0xf8, 0xc6, 0x93, 0x8d, 0x6c, 0xd3, 0xb2, 0x78, 0x85, 0xf1, 0x7a, 0x09, 0x5f, 0x41,
	0xd8, 0xfa, 0x89, 0xbc, 0x3d, 0x6f, 0x41, 0xed, 0xd8, 0xe2, 0x7c, 0xce, 0xb8, 0x23, 0xdb, 0xc1,
	0xbf, 0x64, 0xfb, 0x1d, 0x82, 0xc6, 0x2f, 0xee, 0x80, 0xaf, 0xc5, 0x0d, 0x35, 0x91, 0xd4, 0x45,
	0x5f, 0xa6, 0x7d, 0x31, 0x7a, 0xbd, 0x31, 0xb2, 0x9f, 0x2e, 0xf8, 0xe6, 0xa8, 0xf8, 0x00, 0xd6,
	0x54, 0x39, 0x56, 0xa4, 0xad, 0xbc, 0xad, 0x90, 0xc1, 0xe6, 0x75, 0x26, 0xc6, 0x71, 0x76, 0x9e,
	0xce, 0x52, 0xad, 0xec, 0x3e, 0x1d, 0x0c, 0x77, 0x21, 0x50, 0xe5, 0x98, 0x97, 0x19, 0x29, 0xbb,
	0x51, 0x5b, 0x63, 0x04, 0xeb, 0xb5, 0x92, 0xb2, 0xd1, 0x36, 0x25, 0xbe, 0x85, 0x87, 0xb5, 0xca,
	0xf1, 0x6d, 0x92, 0x95, 0x13, 0xfa, 0xdc, 0x66, 0x19, 0xf9, 0x7b, 0xde, 0x30, 0xe4, 0x77, 0x2d,
	0xe3, 0x17, 0xd8, 0x51, 0x94, 0xab, 0x91, 0x11, 0x5a, 0x68, 0x5b, 0x33, 0xd1, 0x3c, 0x6e, 0xff,
	0xa2, 0xab, 0x14, 0xde, 0xdb, 0xc8, 0x3e, 0xc1, 0x4e, 0x1f, 0xbb, 0x1d, 0xae, 0xb3, 0x30, 0xdc,
	0xa7, 0x00, 0xf3, 0x5b, 0x17, 0xb9, 0xc6, 0xe9, 0x02, 0xc2, 0x4e, 0x20, 0x68, 0x2e, 0x45, 0x6f,
	0xff, 0x7c, 0xd0, 0x6e, 0x67, 0xd0, 0x5b, 0xe0, 0xa6, 0x85, 0x1d, 0x9f, 0x9b, 0x16, 0xec, 0x04,
	0x70, 0xf5, 0x92, 0xe0, 0x21, 0xdc, 0x1f, 0x67, 0x22, 0xb9, 0x39, 0xa7, 0x78, 0x42, 0xf2, 0x38,
	0xa3, 0xfa, 0x72, 0x55, 0x1b, 0x04, 0xbc, 0x6f, 0xe9, 0xe8, 0x14, 0xb6, 0xac, 0x4e, 0x46, 0xf2,
	0x82, 0xd4, 0x14, 0xdf, 0x40, 0xc0, 0xe9, 0x3a, 0x55, 0x9a, 0x24, 0xa2, 0x1d, 0xd6, 0xc2, 0xab,
	0xb7, 0x7b, 0xaf, 0x83, 0x15, 0x94, 0xb0, 0xff, 0x86, 0xce, 0xa1, 0xf3, 0x61, 0xfd, 0x5b, 0xfd,
	0x4c, 0x8e, 0xd7, 0xcc, 0xe7, 0xf5, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4d, 0xfd, 0x12, 0xe1,
	0x5a, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ControllerMeshClient is the client API for ControllerMesh service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ControllerMeshClient interface {
	Register(ctx context.Context, opts ...grpc.CallOption) (ControllerMesh_RegisterClient, error)
}

type controllerMeshClient struct {
	cc *grpc.ClientConn
}

func NewControllerMeshClient(cc *grpc.ClientConn) ControllerMeshClient {
	return &controllerMeshClient{cc}
}

func (c *controllerMeshClient) Register(ctx context.Context, opts ...grpc.CallOption) (ControllerMesh_RegisterClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ControllerMesh_serviceDesc.Streams[0], "/proto.ControllerMesh/Register", opts...)
	if err != nil {
		return nil, err
	}
	x := &controllerMeshRegisterClient{stream}
	return x, nil
}

type ControllerMesh_RegisterClient interface {
	Send(*ProxyStatus) error
	Recv() (*ProxySpec, error)
	grpc.ClientStream
}

type controllerMeshRegisterClient struct {
	grpc.ClientStream
}

func (x *controllerMeshRegisterClient) Send(m *ProxyStatus) error {
	return x.ClientStream.SendMsg(m)
}

func (x *controllerMeshRegisterClient) Recv() (*ProxySpec, error) {
	m := new(ProxySpec)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ControllerMeshServer is the server API for ControllerMesh service.
type ControllerMeshServer interface {
	Register(ControllerMesh_RegisterServer) error
}

// UnimplementedControllerMeshServer can be embedded to have forward compatible implementations.
type UnimplementedControllerMeshServer struct {
}

func (*UnimplementedControllerMeshServer) Register(srv ControllerMesh_RegisterServer) error {
	return status.Errorf(codes.Unimplemented, "method Register not implemented")
}

func RegisterControllerMeshServer(s *grpc.Server, srv ControllerMeshServer) {
	s.RegisterService(&_ControllerMesh_serviceDesc, srv)
}

func _ControllerMesh_Register_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ControllerMeshServer).Register(&controllerMeshRegisterServer{stream})
}

type ControllerMesh_RegisterServer interface {
	Send(*ProxySpec) error
	Recv() (*ProxyStatus, error)
	grpc.ServerStream
}

type controllerMeshRegisterServer struct {
	grpc.ServerStream
}

func (x *controllerMeshRegisterServer) Send(m *ProxySpec) error {
	return x.ServerStream.SendMsg(m)
}

func (x *controllerMeshRegisterServer) Recv() (*ProxyStatus, error) {
	m := new(ProxyStatus)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _ControllerMesh_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ControllerMesh",
	HandlerType: (*ControllerMeshServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Register",
			Handler:       _ControllerMesh_Register_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "apis/ctrlmesh/proto/ctrlmesh.proto",
}
